name: Production UI deployment

on:
  push:
    branches:
      - main


jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1.0.1
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          dokku-host: "3.109.174.170"
          ssh-port: "22"
          app-name: "digisky-backend"
          git-push-flags: "--force"
